### PR TITLE
Updated to work with Leaflet 1.0; bumped version to 0.3.0

### PR DESCRIPTION
**Pull request by chugcup**
The L.Control.Layers class changed in Leaflet 1.0+ to store the
`_layers` object as a list rather than using an Object with
the `L.stamp()` (layerId) as keys.  This broke retrieval of overlays.

Old format:
  `  _layers : { 1: {layer: ..., name: ...}, 104: {layer: ..., name: ... } }`
New format:
  `  _layers : [ {layer: ..., name: ... }, {layer: ..., name: ... } ]`

The `L.stamp()` value can be retrieved using `layer._leaflet_id` in this
scenario, so the return value from getActiveOverlayLayers() has not
changed.

After this change, the plugin should be compatible with both the
Leaflet 0.7.x and 1.0 branches.

### CODE REVIEW

**Comment by vogdb** [comment]
Wow! Great job done! What do you think about using `Array.isArray` instead of `instanceof`?

**Comment by chugcup** [comment]
I have no issue with that.  See added commit.

**Comment by vogdb** [comment]
Thank you so much! Perfetto!

**Comment by vogdb** [comment]
🎉 https://github.com/vogdb/Leaflet.ActiveLayers/releases/tag/0.3.0

**Pull request merged**
