### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by bkrrr**
add main property

### CODE REVIEW

**Comment by vogdb** [comment]
Please update version to 0.2.1 in package.json and bower.json.

**Comment by vogdb** [comment]
well, I meant to update them here, so we will release a new version with your patch immediately after merge. Is that fine with you?

**Comment by bkrrr** [comment]
i´m new to github.... i guess, i messed it up a little bit :).
yes, that would be great.

**Comment by vogdb** [comment]
So, just add the changes here :) For that you need to make them in your branch `patch-1` and push them to your repo `git@github.com:bkrrr/Leaflet.ActiveLayers.git`.

**Comment by vogdb** [comment]
I believe that you can do it :+1:

**Pull request closed without merging**
